### ISSUE TITLE
Pin the hash of graph.snapshot-mainnet.zlib for reproducibility

### ISSUE THREAD

**Issue by Giszmo** [btcontract/wallet#103]
GitHub Releases are editable and not cryptographically hashed. Build instructions include downloading `graph.snapshot-mainnet.zlib` from the release. Reproducible builds for older versions will fail if for example GitHub disappears.

Ideally the file would be part of the main git repository or if for any reason this is not ok, the file could be versioned in a git submodule.

If all that are no options, please add the binary blob's hash to the main repository and reject files with different hash (unless compile parameter allows this, if required).

**Comment by btcontract** [comment]
Fixed in release: https://github.com/btcontract/wallet/releases/tag/2.4.19. 

Snapshot file size has been reduced to ~600kb here: https://github.com/btcontract/wallet/blob/master/app/src/main/assets/graph.snapshot-mainnet.zlib so from now on it will be a part of repository and there is no need to download an external file.
