### ISSUE TITLE
Remove "Buy Bitcoin" button

### ISSUE THREAD

**Issue by ghost** [btcontract/wallet#18]
This is a "wallet" app. A "Wallet" is only for spent your money, not for advertising.
Also, the user who wants to buy BTC should educate themselves and select *who* to trust.

So, keep this app simple.

**Comment by btcontract** [comment]
This was my initial sentiment, too, but people kept asking about how and where to purchase bitcoins so I guess having a buy option in a menu is appropriate. Also both Localbitcoins and Glidera have a good reputation as far as I know.

**Comment by GitHubHatesTor** [comment]
How about adding a new option named "Hide Buy link from GUI"?

**Comment by tracihaire** [comment]
I think someone has hacked in to my phone again

**Comment by btcontract** [comment]
@tracihaire what is going on exactly?

**Comment by tracihaire** [comment]
Not sure someone keep trying to get in my phone that take it over and I watch them talk and have conversation with different  people and they delet thing

**Comment by btcontract** [comment]
@tracihaire okay I'd suggest you to stop using Bitcoin wallet there. If you have wallet's [mnemonic code](https://btcontract.com/#mnemonic-code) saved then fine, just delete a wallet app and restore your balance on another device. If not then your best bet is to send all the funds in a single transaction to another wallet of yours installed on another device.

Or you may do nothing and try to remove malware using antivirus or some local service I guess.

**Comment by tracihaire** [comment]
I opened like 20 app looking at them an put the address in them I have been working on this for days  trying to understand all of it and I think I finally  figured  it out at least I hope but I did think of a great idea for a wallet 
Instead of it saying send and receive   may be it should be depoist and take out or spend  with your address for depoist as ur user name   and if ur sending it maybe have a area for a desteation as well  as that person or company name   and if u want to put it in ur bank have it say transform to bank that simple   and I have had the hardest time trying to figure  out the blocks and the amount of them but the only one I could really understand was coinmill   and have it all on the page together 
I just hope I'm do I g this right lol

**Comment by btcontract** [comment]
@tracihaire okay it's not at all hard to lose your coins if you don't know what are you doing in Bitcoin and this seems to be your case. First, please read and understand a wallet manual here: https://btcontract.com/, then do more research if needed, there are a lot of various manuals on the internet.
