### ISSUE TITLE
Option to set custom fee rate

### ISSUE THREAD

**Issue by rohithpr** [btcontract/wallet#22]
Would it be possible to add an option to set a custom fee rate? At the moment, the two options are 0.0001 and and 0.001xyz which is around 15 times the lower option. (Maybe even add the option to set a fixed fee instead of a rate.)

Probably unrelated, but would it be possible to display how much fee is actually going to be charged? (calclating "0.0001 per kB" mentally requires abilities that I do not have 😢)

**Comment by btcontract** [comment]
Yeah, it's not very informative and quite outdated given the fee market situation. I'll rework it completely in the coming days once I get some free time.

**Comment by julian-goldsmith** [comment]
The option to display the fee for the entire transaction would be helpful.  

I recently sent myself some BTC from a wallet that had been receiving small amounts of mined coins for quite a while.  About 2/3 of the BTC I sent (about $200 total) went to fees, due to the large number of inputs.  Had I been able to see how much the transaction would cost, I would have chosen a lower fee.
