### ISSUE TITLE
new update says incompatible and won't install

### ISSUE THREAD

**Issue by hughdavenport** [btcontract/wallet#27]
Tried via fdroid and also direct download off github. Both fail to install

**Comment by btcontract** [comment]
This is strange. A few last updates have no global changes, just a small features like adding a trusted node or connecting to developer nodes by default. Are you trying to install it on a new device?

**Comment by hughdavenport** [comment]
Same device, it wasn't showing new versoin in fdroid until I updated fdroid itself. Installing from google play after uninstalling works fine

**Comment by btcontract** [comment]
Aha, so this seems to be specific to fdroid. Thanks for reporting, I'll look into it.

**Comment by bgaluszka** [comment]
Can confirm that it won't install/update from F-Droid (I've previous version). Incompatibility issue is that current version requires "x86_64".

**Comment by btcontract** [comment]
@bgaluszka thanks for getting to the bottom of it, do you by any chance have an idea how to fix it?

I've just copied https://github.com/btcontract/wallet/blob/master/app/prepare_fdroid.sh and https://github.com/btcontract/wallet/blob/master/app/scrypt_Makefile.patch from https://github.com/greenaddress/WalletCordovaFdroid to make it work for Fdriod and did not actually change them since.

**Comment by bgaluszka** [comment]
@btcontract unfortunately I'm not Android dev :/ From what you write I can only guess that maybe your building environment changed and scrypt only builds for x86_64 causing whole app to require that platform.

**Comment by AreYouLoco** [comment]
Yup it seems like it was build for different architecture:

![Screenshot_20190324-202852](https://user-images.githubusercontent.com/6299176/54884635-abada400-4e73-11e9-8a5f-0aad283c285c.png)

And its still the case 2 years later.
