### ISSUE TITLE
Can't connect to other nodes

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#49]
For some reason a lot of nodes (my own included) can't be connected to. 
![Screenshot_20210821-173445](https://user-images.githubusercontent.com/184066/130325180-16960a45-cb3b-4efe-96dc-e36c0537de23.png)
Same with Breez, Bitrefill etc. I personally run `lnd` and it indeed has data loss protection feature enabled (from `lncli getinfo`):
```
    "features": {
        "0": {
            "name": "data-loss-protect",
            "is_required": true,
            "is_known": true
        },
```
I can connect to ACINQ which seems to use (mostly) the same implementation BLW uses but I want to use my own node and I can't. I have zero issues using my node with Breez or BlueWallet (via my LndHub installation but still) for example.

**Comment by btcontract** [comment]
This is a known degradation in BLW: there were some changes in network protocol which were not applied to that wallet so it can't connect to many nodes and interprets the failure reason wrongly (it's not about data loss protect).

Now, BLW has been deprecated, this is the reason fix has not been applied to it. This repository has no relation to BLW, it's about a different wallet called Simple Bitcoin Wallet (SBW) where all the development is happening now.

This won't be fixed in BLW, you are advised to move to SBW instead, a bit more info on this: https://lightning-wallet.com/posts/blw-is-deprecated/

**Comment by rkfg** [comment]
Thanks! However, [the GP page](https://play.google.com/store/apps/details?id=com.btcontract.wallet) still links to this repo as well as the [main page](https://lightning-wallet.com/). Where's the actual updated source code?

**Comment by btcontract** [comment]
Yeah, the deprecated BLW one (and the one you're using) is https://play.google.com/store/apps/details?id=com.lightning.walletapp

SBW is at https://play.google.com/store/apps/details?id=com.btcontract.wallet
