### ISSUE TITLE
Remove android:requestLegacyExternalStorage="true" or change to false for enforced scoped storage usage 

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#55]
From AndroidManifest:
https://github.com/btcontract/wallet/blob/5d03e156522472500270e99535bf3ded45f3dbcf/app/src/main/AndroidManifest.xml#L25

change the setting to `false` or remove it in order to use scoped storage that limit not needed access of the app to user data.
also the below change is needed (the addition of `android:maxSdkVersion="28"` to `WRITE_EXTERNAL_STORAGE` permission)
https://github.com/btcontract/wallet/blob/5d03e156522472500270e99535bf3ded45f3dbcf/app/src/main/AndroidManifest.xml#L6

Read for more info: https://developer.android.com/training/data-storage/shared/media#request-permissions

**Comment by btcontract** [comment]
This will require some code changes and additional testing in particular in https://github.com/btcontract/wallet/blob/master/app/src/main/java/com/btcontract/wallet/utils/LocalBackup.scala. 

I've decided to do this once `compileSdkVersion` moves up from current `29`, which will happen at some point before October due to Play store requirements.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/11142e78f2a8c1bb0c369e67b1ee446f14a25bb5.
