### ISSUE TITLE
Upgrade NDK to supported version

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#74]
The NDK version used as mentioned in README:
https://github.com/btcontract/wallet/blob/89f42fdbd6e081f4e3635f27c4af8c6519cbb32f/README.md#L33
and in:
https://github.com/btcontract/wallet/blob/b5276f4a8c6f8d11a3b9acdbce5da734ced07f34/app/build.gradle#L11

is downloaded from page "Unsupported Downloads" (the "21e")
https://github.com/android/ndk/wiki/Unsupported-Downloads#r21e

> Note: these obsolete versions of the NDK are no longer supported. Use a current release instead.

pages that show supported versions are:
https://developer.android.com/ndk/downloads/#older-downloads
https://github.com/android/ndk/wiki

**Comment by btcontract** [comment]
Current `23.0.7599858` release fails to build an app because of missing toolchains, I assume the reason is again that wallet targets some older phone architectures circa API21. 

I've updated NDK version to `22.1.7171670` in https://github.com/btcontract/wallet/commit/8b5b342ce84d31c997d9844e9bc0aadc4dd428b9, the most recent one which compiles an app successfully without adding toolchains manually.

**Comment by btcontract** [comment]
Closing assuming this is fine, feel free to reopen if this is problematic somehow.
